### GET /
GET http://localhost:8000
Accept: application/json

### GET /api/v1/devices/status/DEV1
GET http://localhost:8000/api/v1/devices/status/DEV1?request_id=1234567890
Accept: application/json

### POST /api/v1/devices/DEV1/commands
POST http://localhost:8000/api/v1/devices/DEV1/commands
Accept: application/json
Content-Type: application/json

{
  "ctrl_id": "1",
  "motion": {
    "mode": 1,
    "params": {
      "left_rpm": 5,
      "right_rpm": 5,
      "steer_angle": 30
    },
    "duration": 10
  }
}
